version: '3.8'
services:
  twitch-downloader:
    image: ghcr.io/julianfbeck/twitch-downloader:latest
    environment:
      - TWITCH_USERNAME
      - DOWNLOAD_DIR
      - MOUNTED_DRIVE
      - CHECK_INTERVAL
      - BOT_TOKEN
      - CHAT_ID
    volumes:
      - /Volumes/Media/other/incomplete:/downloads
      - /Volumes/Media/other/twitch:/mnt/mounted_drive

