version: '3.8'
services:
  twitch-downloader:
    build: .
    environment:
      - TWITCH_USERNAME=melkey
      - DOWNLOAD_DIR=/usr/src/app/downloads
      - MOUNTED_DRIVE=/mnt/mounted_drive
      - CHECK_INTERVAL=300

    volumes:
      - /Volumes/Media/other/incomplete:/downloads
      - /Volumes/Media/other/twitch:/mnt/mounted_drive
